### ISSUE TITLE
Correction on the usage description with IQ-TREE

### ISSUE THREAD

**Issue by bqminh** [evolbioinfo/booster#1]
The Booster code is well written, great job! I was able to integrate it into IQ-TREE in less than one day.
I have only a small concern regarding the README file when describing the use of Booster with IQ-TREE. TBE was designed to correct for the conservative behaviour of Felsenstein's bootstrap but not ultrafast bootstrap. In fact the ultrafast bootstrap already has some correction and thus applying a "double correction" is not valid. Therefore, I would modify it to something like:

```
# Infer ML tree + standard bootstrap trees
iqtree-omp -s align.phy -m GTR -b 100 -nt 5
# Compute booster supports
booster -a tbe -i align.phy.treefile -b align.phy.boottrees -@ 5 -o booster.nw
```

Cheers, Minh

**Comment by fredericlemoine** [comment]
Dear Minh,
Great news! Thanks for your comment, I modified the README.
Cheers, Frederic
