### ISSUE TITLE
Installation with Anaconda

### ISSUE THREAD

**Issue by Matt-BF** [evolbioinfo/booster#2]
Hi! Great job with BOOSTER, just read the paper and will implement it on my analysis!
This is not really an issue, just want to say that I have added BOOSTER to bioconda, so that people that use conda as an environment for their programs can install it easily, with : 
`conda install -c bioconda booster`

Here is the link for anaconda cloud
https://anaconda.org/bioconda/booster

**Comment by fredericlemoine** [comment]
Hi, thanks for adding it to bioconda!
