### ISSUE TITLE
Segmentation Fault when Running from Command Line

### ISSUE THREAD

**Issue by mattjones315** [evolbioinfo/booster#4]
Hello, 

I would like to use booster to assess branch support for some trees of mine and am running into issues when running the tool via command line. 

Specifically, I am using this call to the package: 

./booster -a fbp -i lg3_tree_greedy_priors.processed.txt -b test_greedy_bootstrap.nwk -@ 5 -o booster.nw

And am promptly getting this log file:

booster : version v0.1.2-3-g91fb005a13
Input Tree      : lg3_tree_greedy_priors.processed.txt
Bootstrap Trees : test_greedy_bootstrap.nwk
Output tree     : booster.nw
Stat file       : None
Algo            : fbp
Count tax move/branch: false
Threads         : 5
Dist cutoff     : 0.300000
Quiet           : false
**Segmentation fault (core dumped)**

As you can see, I am getting a seg fault from my data input, but fail to understand why this is happening.

Some more information about my input: 
- my reference file is a newick-formatted file
- my test bootstrap dataset is a set of newick-formatted trees, each reconstructed from a bootstrapped sample of the original character matrix, and each tree is on a new line in the file. 

I'm happy to send my data over via email, thank you in advance for your help! 

-Matt Jones

**Update**: I have tried to run using the server and received a GalaxyError response after ~20min (so I am unsure if this issue is at the beginning or end of the analysis).

**Comment by fredericlemoine** [comment]
Hello, 
Thanks for your feedback about booster.
Could you send me the tree files by e-mail such that I can have a look?
Frederic

**Comment by fredericlemoine** [comment]
So the problem was due to non usual newick format, with tip names surrounded with parentheses, such as:
```
((T1),(T2))
```
This should be resolved soon with the new parser we implemented [here](https://github.com/thekswenson/booster/tree/speed_fl_ks)
