### ISSUE TITLE
FBP Support > 1

### ISSUE THREAD

**Issue by mattjones315** [evolbioinfo/booster#6]
Hello, 

First off, thank you so much for this brilliant work & software! I've found it very useful for assessing supports on my trees. 

I did run into a slight issue, I believe, with some of the results from the FBP mode though. For the output I'm attaching, I'm finding FBP supports greater than 1:

((1_2012210001:1.000000,3_2012210001:1.000000)0.000000:1.000000,(4_2212210001:1.000000,2_2112210001:1.000000)1.500000:1.000000);

My understanding is that the FBP should be [0, 1] always, but is this necessarily the case? And if it is the case, why could I be getting supports > 1? 

I'm attaching the trees I used as input, and I've run the program as so from command line:

./booster -i test_ref.txt -b test_boot.txt -o test_fbp.txt -a fbp 

Thank you in advance! 

Best,
Matt 

[test_ref.txt](https://github.com/evolbioinfo/booster/files/4669832/test_ref.txt)
[test_boot.txt](https://github.com/evolbioinfo/booster/files/4669833/test_boot.txt)

**Comment by fredericlemoine** [comment]
Hello,

Thank you for your comment. I could check with your trees, and it seems that these are rooted trees (and in `test_boot.txt` it is a mix of rooted an unrooted trees).
I corrected the computation, could you please tell me if it works with your trees now?
Thank you,

Frederic

**Comment by mattjones315** [comment]
Fantastic, thank you!

Is the new code on github? If so, I'll repull and verify that it works.
Thanks again!

- Matt

**Comment by fredericlemoine** [comment]
It is on github, you can pull the last changes

Frederic

**Comment by mattjones315** [comment]
Great, thanks! 

I have just repulled the code and upon trying to re-run the code, I encountered a segmentation fault. It appears to happen on the 6th tree: 

**************************
*         Options        *
**************************
booster : version v0.1.2-3-g91fb005a13
Input Tree      : test_ref.nwk
Bootstrap Trees : test_boot.nwk
Output tree     : test_fbp.txt
Stat file       : None
Algo            : fbp
Count tax move/branch: false
Threads         : 1
Dist cutoff     : 0.300000
Quiet           : false
**************************
Num trees: 8
New bootstrap tree : 0
New bootstrap tree : 1
New bootstrap tree : 2
New bootstrap tree : 3
New bootstrap tree : 4
New bootstrap tree : 5
Segmentation fault (core dumped)


Do you have any thoughts on why this might be happening? Did you say that with your changes you were able to compute the FBP correctly on these inputs? 

Thanks again! 

-Matt

**Comment by fredericlemoine** [comment]
Sorry, it should work now

**Comment by mattjones315** [comment]
Fantastic, it works now! Thanks so much. I'll close the issue now.
